added Error Dialogs in all UI Components to inform the User if an Error occurs
aleksn41/corona_world_app pull request #56
Opened 2021-01-12 14:58 UTC by aleksn41

2021-01-14 08:36 UTC, Prom3thean requested changes
We should discuss how we handle the messaging.

2021-01-14 08:36 UTC, Prom3thean commented on app/src/main/java/de/dhbw/corona_world_app/ui/statistic/StatisticFragment.java
> +                ErrorDialog.createBasicErrorDialog(getContext(), "We were not able to create new Files", "Please restart the application or it will not function properly", null);
Very nice error message but I think a "Please restart the app" without the second part suffices

2021-01-14 08:36 UTC, Prom3thean commented on app/src/main/java/de/dhbw/corona_world_app/ui/statistic/StatisticFragment.java
> +                ErrorDialog.createBasicErrorDialog(getContext(), "We were not able to create new Files", "Please restart the application or it will not function properly", null);
We should discuss if we make standardized error codes (e.g. "Error F212" or something along those lines)

2021-01-14 08:36 UTC, Prom3thean commented on app/src/main/java/de/dhbw/corona_world_app/ui/statistic/StatisticFragment.java
> +            Toast.makeText(getContext(), "Could not save Data of this Session, please restart the Application if you want your Session to be saved", Toast.LENGTH_LONG).show();
Same as above...

2021-01-14 08:36 UTC, Prom3thean commented on app/src/main/java/de/dhbw/corona_world_app/ui/tools/StatisticCallRecyclerViewFragment.java
> +                    ErrorDialog.createBasicErrorDialog(getContext(),"An critical Error has occurred","It seems that something unexpected happened, please restart the App and if that does not help rei
Same problem as above. "Please reinstall" seems a tad extreme... I don't know if a user who gets this message will ever reinstall the app.

2021-01-14 08:36 UTC, Prom3thean commented on app/src/main/java/de/dhbw/corona_world_app/ui/tools/StatisticCallRecyclerViewFragment.java
> +            Toast.makeText(getContext(), "Could not save Data of this Session, please restart the Application if you want your Session to be saved", Toast.LENGTH_LONG).show();
Same problem as above. We should discuss.

2021-01-14 08:36 UTC, Prom3thean commented on app/src/main/java/de/dhbw/corona_world_app/ui/tools/StatisticCallRecyclerViewFragment.java
> +                ErrorDialog.createBasicErrorDialog(getContext(), "We were not able to recover your Data", "Your History and your Favourites must be deleted for this app to function properly, we are s
What is this error message?

2021-01-14 08:36 UTC, Prom3thean commented on app/src/main/java/de/dhbw/corona_world_app/ui/tools/StatisticCallRecyclerViewFragment.java
> +        ErrorDialog.createBasicErrorDialog(getContext(), "Your Data seems to be corrupt", "We were not able to save new Data, we will try to fix this Problem", (dialog, which) -> {
Fine error message, but as stated above, we should discuss if we replace some of it with a standardized error code/message

2021-01-14 08:36 UTC, Prom3thean commented on app/src/main/java/de/dhbw/corona_world_app/ui/tools/StatisticCallRecyclerViewFragment.java
> +                        ErrorDialog.createBasicErrorDialog(getContext(),"There has been an error deleting your Data","Something has gone terribly wrong, please reinstall the app and try again",null);
Look above. "Reinstall the app" should not be a message we want to give the user...

2021-01-15 10:25 UTC, aleksn41 commented
Error Codes are now standardized and displayed to User in all UI related Errors

2021-01-17 16:17 UTC, Prom3thean approved these changes

2021-01-17 16:17 UTC, merged